[ray]
local_mode = true
log_level = "WARN" # 'INFO' or 'DEBUG are other options
num_cpus_per_worker = 4


[env]
effect = "formant"
feature_extractors = ["rms", "mfcc"]
source = "noise.wav"
target = "chords_5s.wav"
metric = "l2_normalized"
eval_interval = 1
debug = true

[agent]
checkpoint_freq = 100
checkpoint_at_end = true
hidden_layers = [64]
activation = "relu"
