[ray]
local_mode = true
log_level = "WARN" # 'INFO' or 'DEBUG are other options
num_cpus_per_worker = 4


[env]
effect = "dist_lpf"
feature_extractors = ["rms", "pitch", "spectral"]
source = "noise.wav"
target = "amen.wav"
metric = "l2_normalized"
live_mode = false

[agent]
checkpoint_freq = 100
checkpoint_at_end = true